const configGlobal = {
    participant_id: 'participant_id',
    family_id: 'family_id',
    file_id: 'file_id',
    ferload_url: 'ferload_url',
    data_type: 'data_type',
    file_size: 'file_size',
    file_name: 'file_name',
    file_format: 'file_format',
    study: 'study',
    study_code: 'study_code',
    studyName: 'study.name',
    studyCode: 'study.study_code',
    name: 'name',
    participants: 'participants',
    submitter_participant_id: 'submitter_participant_id',
    data_access_codes: 'data_access_codes',
    access_limitations: 'access_limitations',
    access_requirements: 'access_requirements',
    fileManifestWantedFields: ['file_id', 'data_type', 'file_size', 'participants.participant_id'],
    contact: 'contact',
    value: 'value',
    fileRequestGetFilesInfoSource: [
        'file_id',
        'study.study_code',
        'study.name',
        'participants.submitter_participant_id',
        'participants.participant_id',
        'file_name',
        'data_type',
        'file_format',
        'study.data_access_codes.access_limitations',
        'study.data_access_codes.access_requirements',
        'study.contact.value',
    ],
};

export default configGlobal;
